<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  1684252 => 'Blue Sky',
  1684254 => 'Blue Sky',
  1684256 => 'Blue Sky',
  1684258 => 'Blue Sky',
  1684731 => 'ASTCA',
  1684733 => 'ASTCA',
  1684770 => 'ASTCA',
);
