<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  22170 => 'Expresso',
  22172 => 'HAYO',
  22176 => 'Tigo',
  22177 => 'Orange',
  22178 => 'Orange',
  22179 => 'ADIE',
);
