<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  509980 => 'Hainet',
  509981 => 'Hainet',
  509982 => 'Hainet',
  509983 => 'Hainet',
  509985 => 'Hainet',
  509995 => 'Hainet',
  509996 => 'Hainet',
  509997 => 'Hainet',
  509998 => 'Hainet',
  509999 => 'Hainet',
);
