<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  59771 => 'Digicel',
  59772 => 'Digicel',
  59774 => 'Digicel',
  59775 => 'Telesur',
  59776 => 'Digicel',
  597770 => 'Telesur',
  597771 => 'Telesur',
  597772 => 'Telesur',
  597773 => 'Telesur',
  597774 => 'Telesur',
  59781 => 'Digicel',
  59782 => 'Digicel',
  59783 => 'Uniqa',
  59784 => 'Uniqa',
  59785 => 'Telesur',
  59786 => 'Telesur',
  59787 => 'Telesur',
  59788 => 'Telesur',
  59789 => 'Telesur',
);
