<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  66800 => 'AIS',
  66801 => 'AIS',
  66802 => 'AIS',
  66803 => 'True Move',
  66804 => 'AIS',
  66805 => 'AIS',
  66806 => 'AIS',
  66807 => 'AIS',
  6680895 => 'dtac',
  6680896 => 'dtac',
  6680897 => 'dtac',
  6680898 => 'dtac',
  66809 => 'True Move',
  66810 => 'AIS',
  66811 => 'AIS',
  66812 => 'AIS',
  66813 => 'DTAC',
  66814 => 'DTAC',
  66815 => 'DTAC',
  66816 => 'DTAC',
  66817 => 'AIS',
  66818 => 'AIS',
  66819 => 'AIS',
  6682 => 'AIS',
  6683 => 'True Move',
  6684 => 'AIS',
  6685 => 'DTAC',
  66854 => 'AIS',
  6686 => 'True Move',
  6687 => 'AIS',
  6688 => 'True Move',
  6689 => 'DTAC',
  6690 => 'DTAC',
  66901 => 'AIS',
  66909 => 'True Move',
  6691 => 'DTAC',
);
/* EOF */