<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  7701 => 'Kcell',
  7702 => 'Kcell',
  7705 => 'Beeline',
  7708 => 'Altel',
  7747 => 'Tele2',
  7771 => 'Beeline',
  7775 => 'Kcell',
  7776 => 'Beeline',
  7777 => 'Beeline',
  7778 => 'Kcell',
);
