<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  96770 => 'Y',
  96771 => 'SabaFon',
  96773 => 'MTN',
  96777 => 'Yemen Mobile',
);
