<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  822 => 'Seül',
  8231 => 'Gyeonggi-do',
  8232 => 'Inchon',
  8233 => 'Gangwon-do',
  8241 => 'Chungcheongnam-do',
  8243 => 'Chungcheongbuk-do',
  8254 => 'Gyeongsangbuk-do',
  8255 => 'Gyeongsangnam-do',
  8261 => 'Jeollanam-do',
  8263 => 'Jeollabuk-do',
  8264 => 'Jeju-do',
);
