<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  7700 => 'АЛТЕЛ',
  7708 => 'АЛТЕЛ',
  7760 => 'Кулан',
  7762 => 'НУРСАТ',
  7763 => 'Арна',
);
