preset: psr2

finder:
  not-path:
    - "src/data/"
    - "src/carrier/data/"
    - "src/geocoding/data/"
    - "src/timezone/data/"
    - "tests/core/data/"
    - "tests/carrier/data/"
    - "tests/prefixmapper/data/"
    - "tests/timezone/data/"
  not-name:
    - "CountryCodeToRegionCodeMap.php"
    - "CountryCodeToRegionCodeMapForTesting.php"
    - "AlternateFormatsCountryCodeSet.php"
    - "ShortNumbersRegionCodeSet.php"
