#!/usr/bin/env php
<?php

if (!file_exists(__DIR__.'/vendor/symfony/phpunit-bridge/bin/simple-phpunit')) {
    echo "Unable to find the `simple-phpunit` script in `vendor/symfony/phpunit-bridge/bin/`.\nPlease run `composer update` before running this command.\n";
    exit(1);
}

putenv('SYMFONY_PHPUNIT_REMOVE_RETURN_TYPEHINT=1');
putenv("SYMFONY_DEPRECATIONS_HELPER=disabled=1");

if (!getenv('SYMFONY_PHPUNIT_VERSION')) {
    if (\PHP_VERSION_ID > 80000) {
        putenv('SYMFONY_PHPUNIT_VERSION=9.5');
    } elseif (\PHP_VERSION_ID > 70400) {
        putenv('SYMFONY_PHPUNIT_VERSION=7.5');
    }
}

require __DIR__.'/vendor/symfony/phpunit-bridge/bin/simple-phpunit';
