<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  1201 => 'NJ',
  1212 => 'NY',
  1212812 => 'New York, NY',
  1617423 => 'Boston, MA',
  1650 => 'CA',
  1650960 => 'Mountain View, CA',
  1989 => 'MA',
);
