<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  1586 => 'Michigan',
  1586263 => 'Clinton Twp, MI',
  1586264 => 'Sterling Heights, MI',
  1586268 => 'Sterling Heights, MI',
  1586274 => 'Sterling Heights, MI',
  1586286 => 'Clinton Twp, MI',
  1586427 => 'Warren, MI',
  1586446 => 'Sterling Heights, MI',
  1586493 => 'Mount Clemens, MI',
  1586498 => 'Saint Clair Shores, MI',
  1586558 => 'Warren, MI',
  1586573 => 'Warren, MI',
  1586574 => 'Warren, MI',
  1586576 => 'Warren, MI',
  1586582 => 'Warren, MI',
  1586598 => 'Chesterfield, MI',
  1586727 => 'Richmond, MI',
  1586751 => 'Warren, MI',
  1586754 => 'Warren, MI',
  1586755 => 'Warren, MI',
  1586756 => 'Warren, MI',
  1586757 => 'Warren, MI',
  1586758 => 'Warren, MI',
  1586759 => 'Warren, MI',
  1586784 => 'Armada, MI',
  1586790 => 'Clinton Twp, MI',
  1586791 => 'Clinton Twp, MI',
  1586792 => 'Clinton Twp, MI',
  1586795 => 'Sterling Heights, MI',
  1586806 => 'Warren, MI',
  1586939 => 'Sterling Heights, MI',
  1586948 => 'Chesterfield, MI',
  1586949 => 'Chesterfield, MI',
  1586977 => 'Sterling Heights, MI',
  1586978 => 'Sterling Heights, MI',
  1586979 => 'Sterling Heights, MI',
);
