<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  1774 => 'Massachusetts',
  1774202 => 'New Bedford, MA',
);
