<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  1980 => 'North Carolina',
  1980207 => 'Charlotte, NC',
  1980224 => 'Charlotte, NC',
  1980343 => 'Charlotte, NC',
  1980487 => 'Shelby, NC',
  1980819 => 'Charlotte, NC',
);
