<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  2422221 => 'Cuvette',
  2422222 => 'Likouala/Sangha',
  2422223 => 'Pool',
  2422224 => 'Plateaux',
  2422225 => 'Bouenza/Lekoumou/Niari',
  2422228 => 'Brazzaville',
  2422229 => 'Pointe-Noire',
);
