<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  2521 => 'Hargeisa',
  25251 => 'Mangauno',
  25261 => 'Mogadishu',
);
