<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  2572220 => 'Bujumbura',
  2572221 => 'Bujumbura',
  2572222 => 'Bujumbura',
  2572223 => 'Bujumbura',
  2572224 => 'Bujumbura',
  2572225 => 'Bujumbura',
  2572226 => 'West zone',
  2572227 => 'Rural areas',
  2572230 => 'North zone',
  2572240 => 'Central east zone',
  2572250 => 'South zone',
);
