<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86350 => 'Xinzhou, Shanxi',
  86351 => 'Taiyuan, Shanxi',
  86352 => 'Datong, Shanxi',
  86353 => 'Yangquan, Shanxi',
  86354 => 'Yuci, Shanxi',
  86355 => 'Changzhi, Shanxi',
  86356 => 'Jincheng, Shanxi',
  86357 => 'Linfen, Shanxi',
  86358 => 'Lishi, Shanxi',
  86359 => 'Yuncheng, Shanxi',
);
/* EOF */