<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86722 => 'Suizhou, Hubei',
  86724 => 'Jingmen, Hubei',
  86728 => 'Xiantao, Hubei',
);
