<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86812 => 'Panzhihua, Sichuan',
  86813 => 'Zigong, Sichuan',
  86816 => 'Mianyang, Sichuan',
  86817 => 'Nanchong, Sichuan',
  86818 => 'Dazhou, Sichuan',
);
/* EOF */