<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86883 => 'Lincang, Yunnan',
  86886 => 'Liuku, Yunnan',
  86887 => 'Zhongdian, Yunnan',
  86888 => 'Lijiang, Yunnan',
);
