<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86990 => 'Kalamayi, Xinjiang',
  86991 => 'Urumchi, Xinjiang',
  86992 => 'Kuitun, Xinjiang',
  86993 => 'Shihezi, Xinjiang',
  86994 => 'Changji, Xinjiang',
  86995 => 'Tulufan, Xinjiang',
  86996 => 'KuErle, Xinjiang',
  86997 => 'Akesu, Xinjiang',
  86998 => 'Kashi, Xinjiang',
  86999 => 'Yining, Xinjiang',
);
