<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  962266 => 'Mafraq',
  962267 => 'Jarash',
  962268 => 'Ajloun',
  962269 => 'Irbid',
  9623222 => 'Tafileh',
  962324 => 'Aqaba',
  962325 => 'Maan',
  9623260 => 'Tafileh',
  962327 => 'Karak',
  962530 => 'Zarqa',
  962531 => 'Madaba',
  962533 => 'Balqa',
  9626 => 'Amman',
);
