<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  22961 => 'MTN',
  22962 => 'MTN',
  22963 => 'Moov',
  22964 => 'Moov',
  22965 => 'Moov',
  22966 => 'MTN',
  22967 => 'MTN',
  22968 => 'Glo',
  22969 => 'MTN',
  22990 => 'Libercom',
  22993 => 'BLK',
  22994 => 'Moov',
  22995 => 'Moov',
  22997 => 'MTN',
  22998 => 'Glo',
  22999 => 'Glo',
);
