<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  23560 => 'Airtel',
  23562 => 'Airtel',
  23563 => 'Airtel',
  23565 => 'Airtel',
  23566 => 'Airtel',
  23568 => 'Airtel',
  2357 => 'Sotel',
  2359 => 'Tigo',
);
