<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  245955 => 'Orange',
  2459560 => 'Orange',
  2459561 => 'Orange',
  2459562 => 'Orange',
  2459650 => 'Spacetel',
  2459651 => 'Spacetel',
  2459652 => 'Spacetel',
  245966 => 'Spacetel',
  245969 => 'Spacetel',
  245977 => 'Guinetel',
);
