<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  245955 => 'Orange',
  245966 => 'Spacetel',
  245969 => 'Spacetel',
  245977 => 'Guinetel',
);
