<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  26095 => 'ZAMTEL',
  26096 => 'MTN',
  26097 => 'Airtel',
);
