<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  26460 => 'Telecom Namibia',
  26481 => 'MTC',
  26482 => 'Telecom Namibia',
  26485 => 'TN Mobile',
);
