<?php

/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return  [
    35051 => 'Gibfibre',
    35052 => 'Gibfibre',
    35054 => 'GibTel',
    35056 => 'GibTel',
    35057 => 'GibTel',
    35058 => 'GibTel',
    350601 => 'Melmasti',
    350606 => 'GibTel',
];
