<?php

/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return  [
    38630 => 'A1',
    38631 => 'Telekom Slovenije',
    38640 => 'A1',
    38641 => 'Telekom Slovenije',
    38643 => 'Telekom Slovenije',
    38649 => 'Telekom Slovenije',
    38651 => 'Telekom Slovenije',
    38664 => 'T-2',
    386651 => 'SŽ - Infrastruktura',
    3866555 => 'Telekom Slovenije',
    3866556 => 'Sloexport',
    386656 => 'SoftNet',
    386657 => 'Novatel',
    386658 => 'Novatel',
    38668 => 'A1',
    38669 => 'A1',
    3866910 => 'Compatel',
    386695 => 'Novatel',
    38670 => 'Telemach',
    38671 => 'Telemach',
];
