<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  593960 => 'CNT',
  593961 => 'CNT',
  5939620 => 'CNT',
  5939621 => 'CNT',
  5939622 => 'CNT',
  5939623 => 'CNT',
  5939624 => 'CNT',
);
