<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  5993181 => 'Eutel',
  5993184 => 'Eutel',
  5993185 => 'Eutel',
  5993186 => 'Eutel',
  5993187 => 'Eutel',
  5993188 => 'Eutel',
  599319 => 'WIC',
  5994161 => 'Satel',
  5994164 => 'WIC',
  5994165 => 'WIC',
  5994166 => 'WIC',
  5994167 => 'WIC',
  5994168 => 'WIC',
  5994169 => 'Satel',
  599700 => 'Digicel',
  599701 => 'Digicel',
  599770 => 'Kla',
  599777 => 'Kla',
  59978 => 'Digicel',
  599790 => 'Chippie',
  599795 => 'Chippie',
  599796 => 'Chippie',
  599951 => 'Chippie',
  599952 => 'Chippie',
  599953 => 'Chippie',
  599954 => 'Chippie',
  599956 => 'Chippie',
  599957 => 'Chippie',
  599961 => 'CSC',
  599963 => 'GSM Caribbean',
  599965 => 'Digicel',
  599966 => 'Digicel',
  599967 => 'Digicel',
  599968 => 'Digicel',
  599969 => 'Digicel',
);
