<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  6661 => 'AIS',
  6664 => 'Penguin SIM',
  6665 => 'AIS',
  6666 => 'DTAC',
  66800 => 'AIS',
  66801 => 'AIS',
  66802 => 'AIS',
  66803 => 'True Move',
  66804 => 'DTAC',
  66805 => 'DTAC',
  66806 => 'AIS',
  66810 => 'AIS',
  66811 => 'AIS',
  66812 => 'AIS',
  66813 => 'DTAC',
  66814 => 'DTAC',
  66815 => 'DTAC',
  66816 => 'DTAC',
  66817 => 'AIS',
  66818 => 'AIS',
  66819 => 'AIS',
  6682 => 'AIS',
  6683 => 'True Move',
  6684 => 'AIS',
  6685 => 'DTAC',
  66854 => 'AIS',
  6686 => 'True Move',
  6687 => 'AIS',
  6688 => 'True Move',
  6689 => 'DTAC',
  6690 => 'DTAC',
  66901 => 'AIS',
  66909 => 'True Move',
  6691 => 'DTAC',
);
