<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  67570 => 'Digicel',
  67571 => 'Digicel',
  67572 => 'Digicel',
  67573 => 'Digicel',
  67574 => 'Digicel',
  67575 => 'bmobile',
  67576 => 'bmobile',
  6757731 => 'Telikom',
  6757732 => 'Telikom',
  6757733 => 'Telikom',
  6757734 => 'Telikom',
  6757735 => 'Telikom',
  6757736 => 'Telikom',
  6757737 => 'Telikom',
  6757738 => 'Telikom',
  6757739 => 'Telikom',
  675775 => 'Telikom',
  675776 => 'Telikom',
  675777 => 'Telikom',
  675778 => 'Telikom',
  675779 => 'Telikom',
  67578 => 'Telikom',
  67579 => 'Digicel',
  67581 => 'DIGIVOIP',
  67588 => 'Digicel',
);
