<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  97331 => 'Royal Court',
  97332 => 'Batelco',
  97333 => 'VIVA',
  97334 => 'VIVA',
  97335 => 'VIVA',
  97336 => 'zain BH',
  97337 => 'zain BH',
  97338 => 'Batelco',
  97339 => 'Batelco',
  97354 => 'VIVA',
  97363 => 'VIVA',
  973663 => 'zain BH',
  973666 => 'zain BH',
  973667 => 'Batelco',
  973669 => 'zain BH',
);
