<?php
/**
 * This file has been @generated by a phing task by {@link GeneratePhonePrefixData}.
 * See [README.md](README.md#generating-data) for more information.
 *
 * Pull requests changing data in these files will not be accepted. See the
 * [FAQ in the README](README.md#problems-with-invalid-numbers] on how to make
 * metadata changes.
 *
 * Do not modify this file directly!
 */

return array (
  822 => 'Seul',
  8241 => 'Chungcheong Południowy',
  8243 => 'Chungcheong Północny',
  8244 => 'Sedżong',
  8251 => 'Pusan',
  8254 => 'Gyeongsang Północny',
  8255 => 'Gyeongsang Południowy',
  8261 => 'Jeolla Południowa',
  8263 => 'Jeolla Północna',
  8264 => 'Czedżu',
);
