<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  822 => 'Seul',
  8241 => 'Chungcheong Południowy',
  8243 => 'Chungcheong Północny',
  8244 => 'Sedżong',
  8251 => 'Pusan',
  8254 => 'Gyeongsang Północny',
  8255 => 'Gyeongsang Południowy',
  8261 => 'Jeolla Południowa',
  8263 => 'Jeolla Północna',
  8264 => 'Czedżu',
);
