<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  822 => 'Seul',
  8241 => 'Chungcheong do Sul',
  8243 => 'Chungcheong do Norte',
  8244 => 'Sejong',
  8254 => 'Gyeongsang do Norte',
  8255 => 'Gyeongsang do Sul',
  8261 => 'Jeolla do Sul',
  8263 => 'Jeolla do Norte',
);
