<?php
/**
 * This file is automatically @generated by {@link BuildMetadataPHPFromXml}.
 * Please don't modify it directly.
 */


return array (
  'generalDesc' => 
  array (
    'NationalNumberPattern' => '
          [14-8]\\d{6,9}|
          [23]\\d{4,9}|
          9(?:
            [0-4]\\d{8}|
            9\\d{2,8}
          )
        ',
    'PossibleNumberPattern' => '\\d{4,10}',
  ),
  'fixedLine' => 
  array (
    'NationalNumberPattern' => '
          1(?:
            [13-589][12]|
            [27][1-4]
          )\\d{7}|
          2(?:
            1\\d{3,8}|
            3[12]\\d{7}|
            4(?:
              1\\d{4,7}|
              2\\d{7}
            )|
            53\\d{7}|
            6\\d{8}|
            7[34]\\d{7}|
            [89][12]\\d{7}
          )|
          3(?:
            1[2-5]\\d{7}|
            2[1-4]\\d{7}|
            3(?:
              [125]\\d{7}|
              4\\d{6,7}
            )|
            4(?:
              1\\d{6,7}
              [24-9]\\d{7}
            )|
            5(?:
              1\\d{4,7}|
              [23]\\d{7}
            )|
            [6-9][12]\\d{7}
          )|
          4(?:
            [135-9][12]\\d{7}|
            2[1-467]\\d{7}|
            4(?:
              1\\d{4,7}|
              [2-4]\\d{7}
            )
          )|
          5(?:
            1[2-5]\\d{7}|
            2[89]\\d{7}|
            3[1-5]\\d{7}|
            4(?:
              1\\d{4,7}|
              [2-8]\\d{7}
            )|
            [5-7][12]\\d{7}|
            8[1245]\\d{7}
          )|
          6(?:
            1(?:
              1\\d{6,7}|
              2\\d{7}
            )|
            [347-9][12]\\d{7}|
            5(?:
              1\\d{7}|
              2\\d{6,7}
            )|
            6[1-6]\\d{7}
          )|
          7(?:
            1[2-5]|
            2[1289]|
            [3589][12]|
            4[1-4]|
            6[1-6]|
            7[1-3]
          )\\d{7}|
          8(?:
            [145][12]|
            3[124578]|
            6[2-6]|
            7[1245]
          )\\d{7}
        ',
    'PossibleNumberPattern' => '\\d{5,10}',
    'ExampleNumber' => '2123456789',
  ),
  'mobile' => 
  array (
    'NationalNumberPattern' => '
          9(?:
            0[12]|
            [1-3]\\d
          )\\d{7}
        ',
    'PossibleNumberPattern' => '\\d{10}',
    'ExampleNumber' => '9123456789',
  ),
  'tollFree' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'premiumRate' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'sharedCost' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'personalNumber' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'voip' => 
  array (
    'NationalNumberPattern' => '
          (?:
            [2-6]0\\d|
            993
          )\\d{7}
        ',
    'PossibleNumberPattern' => '\\d{10}',
    'ExampleNumber' => '9932123456',
  ),
  'pager' => 
  array (
    'NationalNumberPattern' => '943\\d{7}',
    'PossibleNumberPattern' => '\\d{10}',
    'ExampleNumber' => '9432123456',
  ),
  'uan' => 
  array (
    'NationalNumberPattern' => '9990\\d{0,6}',
    'PossibleNumberPattern' => '\\d{4,10}',
    'ExampleNumber' => '9990123456',
  ),
  'emergency' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'voicemail' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'shortCode' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'standardRate' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'carrierSpecific' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'noInternationalDialling' => 
  array (
    'NationalNumberPattern' => 'NA',
    'PossibleNumberPattern' => 'NA',
  ),
  'id' => 'IR',
  'countryCode' => 98,
  'internationalPrefix' => '00',
  'nationalPrefix' => '0',
  'nationalPrefixForParsing' => '0',
  'sameMobileAndFixedLinePattern' => false,
  'numberFormat' => 
  array (
    0 => 
    array (
      'pattern' => '(21)(\\d{3,5})',
      'format' => '$1 $2',
      'leadingDigitsPatterns' => 
      array (
        0 => '21',
      ),
      'nationalPrefixFormattingRule' => '0$1',
      'domesticCarrierCodeFormattingRule' => '',
    ),
    1 => 
    array (
      'pattern' => '(2[15])(\\d{3})(\\d{3,4})',
      'format' => '$1 $2 $3',
      'leadingDigitsPatterns' => 
      array (
        0 => '
            2(?:
              1|
              5[0-47-9]
            )
          ',
      ),
      'nationalPrefixFormattingRule' => '0$1',
      'domesticCarrierCodeFormattingRule' => '',
    ),
    2 => 
    array (
      'pattern' => '(\\d{2})(\\d{4})(\\d{4})',
      'format' => '$1 $2 $3',
      'leadingDigitsPatterns' => 
      array (
        0 => '
            2[156]|
            31|
            51|
            71|
            86
          ',
      ),
      'nationalPrefixFormattingRule' => '0$1',
      'domesticCarrierCodeFormattingRule' => '',
    ),
    3 => 
    array (
      'pattern' => '(\\d{3})(\\d{3})(\\d{3,4})',
      'format' => '$1 $2 $3',
      'leadingDigitsPatterns' => 
      array (
        0 => '
            [13-9]|
            2[02-47-9]
          ',
      ),
      'nationalPrefixFormattingRule' => '0$1',
      'domesticCarrierCodeFormattingRule' => '',
    ),
    4 => 
    array (
      'pattern' => '(\\d{3})(\\d{2})(\\d{2,3})',
      'format' => '$1 $2 $3',
      'leadingDigitsPatterns' => 
      array (
        0 => '
            [13-9]|
            2[02-47-9]
          ',
      ),
      'nationalPrefixFormattingRule' => '0$1',
      'domesticCarrierCodeFormattingRule' => '',
    ),
    5 => 
    array (
      'pattern' => '(\\d{3})(\\d{3})',
      'format' => '$1 $2',
      'leadingDigitsPatterns' => 
      array (
        0 => '
            [13-9]|
            2[02-47-9]
          ',
      ),
      'nationalPrefixFormattingRule' => '0$1',
      'domesticCarrierCodeFormattingRule' => '',
    ),
  ),
  'intlNumberFormat' => 
  array (
  ),
  'mainCountryForCode' => false,
  'leadingZeroPossible' => false,
  'mobileNumberPortableRegion' => false,
);
