<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  2431 => 'Kinshasa',
  2432 => 'Katanga',
  2433 => 'Bas-Congo/Bandundu',
  2434 => 'Kasai-Oriental/Kasai-Occidental',
  2435 => 'Province Orientale (Kisanga/Mbandaka)',
  2436 => 'Nord-Kivu/Sud-Kivu/Maniema',
);
