<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  9370 => 'افغان بی سیم',
  937280 => 'روشن',
  93729 => 'روشن',
  93744 => 'افغان تلکام',
  93747 => 'افغان تلکام',
  9375 => 'افغان تلکام',
  9376 => 'ام تی ان',
  9377 => 'ام تی ان',
  9378 => 'اتصالات',
  9379 => 'روشن',
);
