<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  822 => 'Seul',
  8231 => 'Gyeonggi-do',
  8233 => 'Gangwon-do',
  8254 => 'Gyeongsangbuk-do',
  8255 => 'Gyeongsangnam-do',
  8264 => 'Insula Jeju',
);
