<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86410 => '辽宁省铁岭市',
  86411 => '辽宁省大连市',
  86412 => '辽宁省鞍山市',
  86413 => '辽宁省抚顺市',
  86414 => '辽宁省本溪市',
  86415 => '辽宁省丹东市',
  86416 => '辽宁省锦州市',
  86417 => '辽宁省营口市',
  86418 => '辽宁省阜新市',
  86419 => '辽宁省辽阳市',
);
