<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86464 => '黑龙江省七台河市',
  86467 => '黑龙江省鸡西市',
  86468 => '黑龙江省鹤岗市',
  86469 => '黑龙江省双鸭山市',
);
/* EOF */