<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86743 => '湖南省湘西土家族苗族自治州',
  86744 => '湖南省张家界市',
  86745 => '湖南省怀化市',
  86746 => '湖南省永州市',
);
