<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86970 => '青海省海北藏族自治州',
  86971 => '青海省西宁市',
  86972 => '青海省海东地区',
  86973 => '青海省黄南藏族自治州',
  86974 => '青海省海南藏族自治州',
  86975 => '青海省果洛藏族自治州',
  86976 => '青海省玉树藏族自治州',
  86977 => '青海省海西蒙古族藏族自治州',
  86979 => '青海省海西蒙古族藏族自治州',
);
