<?php
/**
 * This file is automatically @generated by {@link GeneratePhonePrefixData}.
 * Please don't modify it directly.
 */

return array (
  86990 => '新疆克拉玛依市',
  86991 => '新疆乌鲁木齐市',
  86992 => '新疆伊犁哈萨克自治州',
  86993 => '新疆石河子市',
  86994 => '新疆昌吉回族自治州',
  86995 => '新疆吐鲁番地区',
  86996 => '新疆巴音郭楞蒙古自治州',
  86997 => '新疆阿克苏地区',
  86998 => '新疆喀什地区',
  86999 => '新疆伊犁哈萨克自治州',
);
